import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  docs: [
    { type: 'category', label: 'Getting started', collapsed: false, items: ['index', 'theming', 'icons'] },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      link: { type: 'doc', id: 'components/index' },
      items: [{ type: 'autogenerated', dirName: 'components' }],
    },
    'migration-v1',
  ],
}

export default sidebars
